name: Docker Image CI

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Force IPv4 and set DNS
        run: |
          echo '{ "dns": ["1.1.1.1"], "ipv6": false }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
          echo "=== Docker daemon.json ==="
          cat /etc/docker/daemon.json

      - name: Login to Docker Hub (with retries & full debug)
        env:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          set -x                     # bash command tracing
          export DOCKER_CLI_DEBUG=1  # Docker CLI debug logs
          for i in 1 2 3 4 5; do
            echo ">>> docker login attempt $i"
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            RC=$?
            if [ $RC -eq 0 ]; then
              echo "Docker login succeeded"
              exit 0
            else
              echo "Docker login failed with code $RC"
              echo "Retrying in 5 seconds..."
              sleep 5
            fi
          done
          echo "ERROR: All docker login attempts failed"
          exit 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sillysuki/fmd2:flare
